_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advanced_text_formatter: 0
  advpoll: 0
  ajax_loader: 0
  audio_embed_field: 0
  audio_embed_media_core: 0
  automated_cron: 0
  bamboo_twig: 0
  bamboo_twig_config: 0
  bamboo_twig_extensions: 0
  bamboo_twig_file: 0
  bamboo_twig_i18n: 0
  bamboo_twig_loader: 0
  bamboo_twig_path: 0
  bamboo_twig_security: 0
  bamboo_twig_token: 0
  better_exposed_filters: 0
  better_local_tasks: 0
  better_social_sharing_buttons: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_content: 0
  blockgroup: 0
  breakpoint: 0
  button_link: 0
  choices: 0
  ckeditor: 0
  ckeditor5: 0
  ckeditor_config: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_devel: 0
  config_filter: 0
  config_ignore: 0
  config_merge: 0
  config_merge_filter: 0
  config_split: 0
  config_translation: 0
  config_update: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  encrypt: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_type_clone: 0
  entity_usage: 0
  entityreference_dragdrop: 0
  entityreference_filter: 0
  facets: 0
  fences: 0
  field: 0
  field_group: 0
  field_ui: 0
  fieldblock: 0
  file: 0
  filter: 0
  fixed_block_content: 0
  focal_point: 0
  geolocation: 0
  google_tag: 0
  hal: 0
  help: 0
  history: 0
  html_tag_usage: 0
  image: 0
  image_widget_crop: 0
  imageapi_optimize: 0
  imageapi_optimize_webp: 0
  imageapi_optimize_webp_responsive: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_button: 0
  jquery_ui_checkboxradio: 0
  jquery_ui_controlgroup: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_region: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  linkit: 0
  locale: 0
  markup: 0
  maxlength: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_entity_browser: 0
  media_entity_browser_media_library: 0
  media_library: 0
  media_responsive_thumbnail: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  migrate: 0
  minifyhtml: 0
  module_filter: 0
  mysql: 0
  name: 0
  node: 0
  oembed_providers: 0
  options: 0
  page_cache: 0
  pagerer: 0
  paragraph_blocks: 0
  paragraph_view_mode: 0
  paragraphs_collapsible: 0
  paragraphs_collection: 0
  paragraphs_entity_embed: 0
  paragraphs_library: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  poll: 0
  protected_pages: 0
  quick_node_clone: 0
  recreate_block_content: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  scheduler: 0
  search_api: 0
  search_api_attachments: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_exclude: 0
  search_api_exclude_entity: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  simple_sitemap_views: 0
  site_verify: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  smart_date: 0
  smart_date_recur: 0
  smart_trim: 0
  social_media_links: 0
  spamspan: 0
  svg_image: 0
  svg_image_field: 0
  svg_image_field_media_bundle: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  taxonomy_multidelete_terms: 0
  telephone: 0
  telephone_formatter: 0
  telephone_validation: 0
  text: 0
  textarea_limit: 0
  time_field: 0
  token: 0
  toolbar: 0
  tracker: 0
  transliterate_filenames: 0
  twig_extensions: 0
  twig_tweak: 0
  tzfield: 0
  update: 0
  upgrade_status: 0
  user: 0
  video_embed_field: 0
  video_embed_spotify: 0
  views_contextual_filters_or: 0
  views_field_view: 0
  views_html_tags: 0
  views_ui: 0
  viewsreference: 0
  webp: 0
  youtube: 0
  extlink: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  bartik: 0
  gin: 0
  olivero: 0
  danaher: 0
profile: standard
