_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - paragraphs_library_item
track_enabled_source_entity_types:
  - contact_message
  - node
  - crop
  - block_content
  - menu_link_content
  - embedded_paragraphs
  - entity_embed_fake_entity
  - media
  - paragraph
  - paragraphs_library_item
  - redirect
  - search_api_task
  - shortcut
  - smart_date_override
  - smart_date_rule
  - taxonomy_term
  - path_alias
  - webform_submission
track_enabled_target_entity_types:
  - contact_message
  - node
  - crop
  - block_content
  - menu_link_content
  - embedded_paragraphs
  - entity_embed_fake_entity
  - media
  - paragraph
  - paragraphs_library_item
  - redirect
  - search_api_task
  - shortcut
  - smart_date_override
  - smart_date_rule
  - taxonomy_term
  - path_alias
  - webform_submission
track_enabled_plugins:
  - dynamic_entity_reference
  - media_embed
  - link
  - linkit
  - layout_builder
  - entity_reference
  - entity_embed
  - html_link
  - block_field
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types:
  - paragraphs_library_item
delete_warning_message_entity_types:
  - paragraphs_library_item
usage_controller_items_per_page: 25
