entity_type_groups:
  media:
    audio:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    document:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
  node:
    directory:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    event:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    high_level_pages:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    homepage:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    page:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
    person:
      open_graph_products: open_graph_products
      basic: basic
      advanced: advanced
      open_graph: open_graph
      facebook: facebook
      twitter_cards: twitter_cards
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_og_description: null
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_title: null
  metatag_maxlength_twitter_cards_label2: null
  metatag_maxlength_twitter_cards_label1: null
  metatag_maxlength_twitter_cards_description: null
  metatag_maxlength_twitter_cards_title: null
tag_scroll_max_height: ''
