_core:
  default_config_hash: ic7i7wf2LjGo4L3xTQNvjkxyQlHjcXexXrFtx-6vWj8
youtube_suggest: false
youtube_modestbranding: true
youtube_theme: false
youtube_color: false
youtube_enablejsapi: true
youtube_wmode: false
youtube_override: true
youtube_privacy: false
youtube_player_class: youtube-field-player
youtube_thumb_dir: youtube
youtube_thumb_hires: true
youtube_thumb_token_image_style: ''
